/**
 * Query-builder webview HTML (pure — no `vscode` import) so both the panel and
 * the UI-interaction harness render the EXACT same page. The inline script
 * collects the spec and posts it to the host; the host answers with the SQL
 * (generated by the tested buildSelectSql — single source of truth). `prelude`
 * is harness-only (stubs `acquireVsCodeApi`); production callers omit it.
 */
import type { FilterOp } from './queryBuilder';

export interface TableRef { schema: string; table: string }

export const QUERY_BUILDER_OPS: FilterOp[] = ['=', '<>', '>', '<', '>=', '<=', 'LIKE', 'ILIKE', 'IN', 'IS NULL', 'IS NOT NULL'];

export interface QueryBuilderHtmlOptions {
  tables: TableRef[];
  columns: string[];
  initialSql: string;
  nonce: string;
  /** Harness-only inline script that runs before the page script. */
  prelude?: string;
}

export function queryBuilderHtml(o: QueryBuilderHtmlOptions): string {
  const tableOpts = o.tables.map((t, i) => '<option value="' + i + '">' + esc(t.schema) + '.' + esc(t.table) + '</option>').join('');
  // Escape `<` so a table/column name containing `</script>` cannot break out
  // of the inline <script> (JSON.stringify does not escape it).
  const data = JSON.stringify({ columns: o.columns, ops: QUERY_BUILDER_OPS, tables: o.tables }).replaceAll('<', '\\u003c');
  const prelude = o.prelude !== undefined ? `<script nonce="${o.nonce}">${o.prelude}</script>` : '';
  return `<!DOCTYPE html><html><head><meta charset="UTF-8">
      <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${o.nonce}';">
      <style>
        body { margin:0; padding:10px 12px; color:var(--vscode-foreground); font-family:var(--vscode-font-family); font-size:13px; }
        h3 { margin:14px 0 6px; font-size:12px; text-transform:uppercase; color:var(--vscode-descriptionForeground); }
        select, input { background:var(--vscode-input-background); color:var(--vscode-input-foreground); border:1px solid var(--vscode-input-border,#555); padding:2px 4px; }
        button { background:var(--vscode-button-background); color:var(--vscode-button-foreground); border:none; padding:4px 10px; margin-right:6px; cursor:pointer; }
        button.sec { background:var(--vscode-button-secondaryBackground); color:var(--vscode-button-secondaryForeground); }
        .cols { display:flex; flex-wrap:wrap; gap:4px 14px; max-height:150px; overflow:auto; border:1px solid var(--vscode-widget-border,#444); padding:6px; }
        .cols label { white-space:nowrap; }
        .frow { display:flex; gap:6px; margin-bottom:4px; align-items:center; }
        pre { background:var(--vscode-textCodeBlock-background,#0000); border:1px solid var(--vscode-widget-border,#444); padding:8px; overflow:auto; white-space:pre-wrap; }
        .bar { margin:8px 0; }
      </style></head><body>
      <h3>Table</h3>
      <select id="table">${tableOpts}</select>
      <label style="margin-left:12px"><input type="checkbox" id="distinct"> DISTINCT</label>
      <label style="margin-left:12px">LIMIT <input type="number" id="limit" value="100" min="0" style="width:70px"></label>
      <h3>Columns <span style="text-transform:none">(none checked = all)</span></h3>
      <div class="cols" id="cols"></div>
      <h3>Filters</h3>
      <div id="filters"></div>
      <button class="sec" id="addFilter">+ filter</button>
      <h3>Order by</h3>
      <div class="frow"><select id="orderCol"></select><select id="orderDir"><option value="">ASC</option><option value="DESC">DESC</option></select></div>
      <h3>SQL</h3>
      <pre id="sql">${esc(o.initialSql)}</pre>
      <div class="bar"><button id="open">Open in editor</button><button class="sec" id="run">Run</button></div>
      ${prelude}<script nonce="${o.nonce}">
        const vscode = acquireVsCodeApi();
        const D = ${data};
        let columns = D.columns.slice();
        const $ = (id) => document.getElementById(id);
        function enc(s){ return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
        function colOptions(withBlank) {
          return (withBlank ? '<option value=""></option>' : '') + columns.map(c => '<option value="'+enc(c)+'">'+enc(c)+'</option>').join('');
        }
        function renderCols(){
          $('cols').innerHTML = columns.map(c => '<label><input type="checkbox" class="ck" value="'+enc(c)+'"> '+enc(c)+'</label>').join('');
          $('orderCol').innerHTML = colOptions(true);
          document.querySelectorAll('.ck').forEach(el => el.addEventListener('change', collect));
          document.querySelectorAll('#filters .fcol').forEach(el => el.innerHTML = colOptions(false));
        }
        function currentTable(){ return D.tables[Number($('table').value)] || D.tables[0]; }
        var NULLARY = { 'IS NULL': 1, 'IS NOT NULL': 1 };
        function syncFilterValue(row){
          // A nullary operator (IS NULL / IS NOT NULL) takes no value — hide the input.
          const nullary = NULLARY[row.querySelector('.fop').value] === 1;
          row.querySelector('.fval').style.display = nullary ? 'none' : '';
        }
        function addFilter(){
          const row = document.createElement('div');
          row.className = 'frow';
          row.innerHTML = '<select class="conn"><option>AND</option><option>OR</option></select>'
            + '<select class="fcol">'+colOptions(false)+'</select>'
            + '<select class="fop">'+D.ops.map(o=>'<option>'+o+'</option>').join('')+'</select>'
            + '<input class="fval" placeholder="value">'
            + '<button class="sec frm">x</button>';
          $('filters').appendChild(row);
          row.querySelectorAll('select,input').forEach(el => el.addEventListener('input', collect));
          row.querySelector('.fop').addEventListener('change', () => { syncFilterValue(row); collect(); });
          row.querySelector('.frm').addEventListener('click', () => { row.remove(); collect(); });
          syncFilterValue(row);
          collect();
        }
        function parseLimit(){
          const v = $('limit').value.trim();
          if (v === '') return undefined;         // blank = no LIMIT
          const n = Math.floor(Number(v));
          return (Number.isFinite(n) && n >= 0) ? n : undefined; // 0 is a real limit
        }
        function buildSpec(){
          const t = currentTable();
          const cols = Array.from(document.querySelectorAll('.ck:checked')).map(el => el.value);
          const filters = Array.from(document.querySelectorAll('#filters .frow')).map((r,i) => {
            const f = { column: r.querySelector('.fcol').value, op: r.querySelector('.fop').value, value: r.querySelector('.fval').value };
            if (i>0) f.connector = r.querySelector('.conn').value;
            return f;
          }).filter(f => f.column);
          const orderCol = $('orderCol').value;
          return { schema: t.schema, table: t.table, columns: cols, filters,
            orderBy: orderCol ? [{ column: orderCol, dir: $('orderDir').value || undefined }] : [],
            limit: parseLimit(), distinct: $('distinct').checked };
        }
        function collect(){ vscode.postMessage({ type:'spec', spec: buildSpec() }); }
        $('table').addEventListener('change', () => {
          const t = currentTable();
          // Filters reference the OLD table's columns — clear them so they don't
          // silently carry over half-configured to the new table (UXD-021).
          $('filters').innerHTML = '';
          vscode.postMessage({ type:'pickTable', schema: t.schema, table: t.table });
        });
        ['distinct','limit','orderCol','orderDir'].forEach(id => $(id).addEventListener('input', collect));
        $('addFilter').addEventListener('click', addFilter);
        // Open/Run send the CURRENT spec (built synchronously now), so the host
        // generates fresh SQL — never the async-lagged preview text (UXD-019).
        $('open').addEventListener('click', () => vscode.postMessage({ type:'open', spec: buildSpec() }));
        $('run').addEventListener('click', () => vscode.postMessage({ type:'run', spec: buildSpec() }));
        window.addEventListener('message', (e) => {
          const m = e.data;
          if (m.type === 'sql') $('sql').textContent = m.sql;
          else if (m.type === 'columns') { columns = m.columns.slice(); renderCols(); collect(); }
        });
        renderCols();
      </script></body></html>`;
}

function esc(s: string): string {
  return s.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
}
